SquaredLabs/squaredlabs.uconn.edu

assets/css/index.css

Description of changes can be found in the commit message. They are meaningful; please take a look.

Create new stacking context for link highlights

---

assets/css/index.css

Use background and overflow for link highlights

---

package.json
webpack.prod.js

The babel-minify-webpack-plugin was giving me a strange error when building. The Webpack builtin production minifier does not seem have this issue.
https://github.com/webpack/webpack-sources/issues/28

Favor webpack -p flag over babel minify plugin

---

.drone.yml

CI builds will fail until #29 and #28 are merged. I'd review those two first.

Setup Drone CI

---

.gitignore
package-lock.json
src/components/BackButton.vue
src/components/ConnectSelect.vue
src/components/Navbar.vue
src/pages/Connect.vue
src/scripts/main.js

Started on connect page
- Added routes, and navs.
- Added headers and some text
- Created component for displaying content to different users
- Created rough styling

Initialize Connect Page

---

src/components/connect/ConnectSelect.vue
src/components/connect/Developer.vue
src/components/connect/Other.vue
src/pages/Connect.vue

Created all the content and styling for the "Other" section of connect page.

Populate "Other" Component

---

src/components/connect/Company.vue
src/components/connect/ConnectSelect.vue
src/components/connect/Developer.vue
src/components/connect/Other.vue
src/components/connect/Student.vue

Using media queries, made all of the connect components viewable on mobile with the same design template as zeplin. Tested with Firefox Responsive Design Tools.

SW-20 Make mobile pages

---

src/components/Link.vue
src/components/connect/Student.vue

- Duplicated CSS from squaredlabs.uconn.edu existing site. 
- Created class binding and prop for blue background. If prop `color="white"` is defined, it renders light blue with white hover so it will appear on a blue background.

SW-22 Update link style

---

src/components/Footbar.vue
src/components/Link.vue
src/components/Navbar.vue
src/pages/Connect.vue
src/pages/Home.vue
src/scripts/main.js

- Created option in link to pass in a function to call
- Changed link fontSize ref to be a string of CSS instead of a number of pixels. Setting fontSize to 1em, 16px, or whatever you want will work
- Replaced Link in navbar and footbar
- Changed navbar css to properly scale on mobile
- Changed the long footbar links to have 0.8em font size so they don't overflow
- Changed link external nav to open in a new tab always

Link extend

---

src/components/Footbar.vue
src/components/Link.vue
src/components/Navbar.vue
src/components/ProjectCard.vue
src/components/connect/Company.vue
src/components/connect/Developer.vue
src/components/connect/Graphics.vue
src/components/connect/Other.vue
src/components/connect/Student.vue
src/pages/home.vue
src/pages/workshops.vue

See commit descriptions.
http://revamp-link-component.squaredlabs.ci.core.uconn.edu/

Revamp link component

---

src/pages/home.vue
src/pages/people.vue
src/pages/projects.vue

Removed v-if from list component as per ESLint's suggestion. Created a parent component instead.

Remove confusing v-if

---

directus.js

Add a bit of help to directus.js #102 #103 #104

---

src/components/LinkParse.vue
src/pages/home.vue
src/pages/people.vue

Created a new component to convert `<a></a>`  tags from CMS into `<SLink/>` components.

#104 Make basic parser for links in CMS

---

src/components/connect/Student.vue

Resolves #115 by removing empty href props.

Connect active links

---

src/assets/styles/_grid.scss
src/components/BackgroundText.vue
src/components/GridLayout.vue
src/components/connect/Company.vue
src/components/connect/ConnectSelect.vue
src/components/connect/Developer.vue
src/components/connect/Graphics.vue
src/components/connect/Other.vue
src/components/connect/Student.vue
src/layouts/default.vue
src/pages/connect.vue
src/pages/projects.vue

Connect page

---

src/components/FullSizePersonCard.vue
src/components/MiniPersonPhoto.vue
src/pages/people.vue

Interactive people page

---

src/components/projects/ProjectCard.vue

Decrease character length for two line project card title

---

src/components/Navbar.vue
src/components/projects/ProjectCard.vue

All branches are failing, this should fix it. Resolves an issue where it was trying to iterate on `project.people` even if it was undefined. Also resolves an issue where document.querySelector() was returning null and we were trying to remove a class from it.

Fix console & build errors

---

src/components/FullSizePersonCard.vue
src/pages/people.vue

Fix people id loading to be dynamic

Refactor some of people page code

---

components/VHighContrastButton.vue
components/VNavbar.vue
layouts/default.vue
store/index.js

High contrast
